<script lang="ts">
	import { ArrowLeft, Building2, Crown, Radio, Save, ShieldCheck, UsersRound } from '@lucide/svelte';
	import type { ActionData, PageData } from './$types';

	let { data, form }: { data: PageData; form: ActionData } = $props();
</script>

<svelte:head><title>Administration | Sanctum Theoretica</title></svelte:head>

<main class="sanctum-page antialiased">
	<header class="sanctum-header"><a href="/" aria-label="Zur Übersicht" title="Zur Übersicht"><ArrowLeft size={18} /></a><div class="brand"><span>ST</span><strong>Kuratorium / Administration</strong></div><div class="owner"><Crown size={15} /> Archivleitung</div></header>
	<section class="shell sanctum-shell"><div class="heading"><div><p class="eyebrow">Owner-Only</p><h1>Administration</h1></div><span>Änderungen werden protokolliert</span></div>
		<form method="POST" action="?/save" class="settings">
			<section class="sanctum-panel"><div class="section-title"><Building2 size={18} /><div><strong>Community</strong><span>Die Guild-ID bestimmt, wo Discord-Commands registriert werden.</span></div></div><label>Discord-Guild-ID<input class="sanctum-control" name="guildId" value={data.config.guildId ?? ''} inputmode="numeric" placeholder="17 bis 20 Ziffern" /></label><p class="notice">Eine geänderte Guild-ID wird gespeichert, benötigt aber einen Bot-Redeploy, bevor Discord die Commands in der neuen Community registriert.</p></section>
			<section><div class="section-title"><UsersRound size={18} /><div><strong>Teamzugang</strong><span>Kommagetrennte Discord-Rollen und zusätzliche Dashboard-Nutzer.</span></div></div><label>Teamrollen-IDs<textarea name="modRoleIds" placeholder="Rollen-ID, Rollen-ID">{data.config.modRoleIds.join(', ')}</textarea></label><label>Zusätzliche Dashboard-Nutzer-IDs<textarea name="dashboardAllowedUserIds" placeholder="Nutzer-ID, Nutzer-ID">{data.config.dashboardAllowedUserIds.join(', ')}</textarea></label><p class="notice">Rollen- und Dashboardzugang werden spätestens nach 30 Sekunden übernommen. Dein Owner-Zugang bleibt außerhalb dieser Liste geschützt.</p></section>
			<section><div class="section-title"><Radio size={18} /><div><strong>Whisper-Betrieb</strong><span>Fallback-Kanal und Zeitfenster der Kuratorin.</span></div></div><label>Fallback-Kanal-ID<input name="whisperChannelId" value={data.config.whisperChannelId ?? ''} inputmode="numeric" placeholder="Optional" /></label><div class="pair"><label>Mindestintervall in Stunden<input name="whisperMinHours" value={data.config.whisperMinHours} type="number" min="1" step="0.5" /></label><label>Höchstintervall in Stunden<input name="whisperMaxHours" value={data.config.whisperMaxHours} type="number" min="1" step="0.5" /></label></div></section>
			<section class="lock"><ShieldCheck size={18} /><div><strong>Geschützte Zugänge</strong><span>Discord-Token, OAuth-Secret, Session-Secret, Datenbank und Bucket-Credentials bleiben ausschließlich bei Railway.</span></div></section>
			{#if form?.error}<p class="error">{form.error}</p>{/if}{#if form?.success}<p class="success">Die Laufzeitkonfiguration wurde gespeichert. Der Bot übernimmt Rollen und Whisper-Parameter innerhalb von 30 Sekunden.</p>{/if}
			<button class="sanctum-button" type="submit"><Save size={16} /> Konfiguration speichern</button>
		</form>
	</section>
</main>

<style>
	main { min-height: 100vh; background: linear-gradient(118deg, rgba(101, 48, 139, .2), transparent 42%), repeating-linear-gradient(0deg, rgba(160, 97, 208, .07) 0 1px, transparent 1px 5px); } header { height: 66px; display: flex; gap: 1rem; align-items: center; padding: 0 5vw; border-bottom: 1px solid var(--line); } header a { display: grid; place-items: center; color: var(--ink); }.brand { display: flex; gap: .6rem; align-items: center; font: .78rem var(--font-ui); letter-spacing: .08em; text-transform: uppercase; }.brand span { display: grid; width: 30px; aspect-ratio: 1; place-items: center; color: #fff; background: var(--surface-deep); font-family: var(--font-display); letter-spacing: 0; }.owner { display: inline-flex; gap: .4rem; align-items: center; margin-left: auto; color: #d5b3ee; font: .72rem var(--font-ui); }.shell { width: min(940px, 90vw); margin: 4rem auto 7rem; }.heading { display: flex; align-items: end; justify-content: space-between; padding-bottom: 1.5rem; border-bottom: 1px solid var(--line); }.eyebrow, .heading > span { margin: 0; color: var(--ink-soft); font: .72rem var(--font-ui); letter-spacing: .1em; text-transform: uppercase; }h1 { margin: .5rem 0 0; font-size: clamp(3rem, 6vw, 5rem); font-weight: 400; line-height: .9; }.settings { display: grid; gap: 1.2rem; margin-top: 2rem; }.settings > section { display: grid; gap: 1rem; padding: 1.35rem; border: 1px solid var(--line); background: var(--surface-raised); }.section-title, .lock { display: flex; gap: .7rem; align-items: flex-start; }.section-title :global(svg), .lock :global(svg) { color: #b36ce8; }.section-title div, .lock div { display: grid; gap: .2rem; }.section-title span, .lock span, .notice { color: var(--ink-muted); font-size: .85rem; line-height: 1.45; }label { display: grid; gap: .45rem; }input, textarea { width: 100%; border: 1px solid var(--line); border-radius: 0; padding: .7rem; color: var(--ink); background: #100914; font: inherit; }textarea { min-height: 64px; resize: vertical; }.pair { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }.notice { margin: 0; padding-left: .7rem; border-left: 2px solid #8952a9; }.lock { padding: .2rem 0; }.error, .success { margin: 0; padding: .75rem; }.error { color: #ff9ab8; border-left: 3px solid var(--danger); }.success { color: #9de1b4; border-left: 3px solid #4b9a66; }button { display: inline-flex; gap: .55rem; align-items: center; justify-content: center; width: max-content; border: 0; padding: .8rem 1rem; color: #fff; background: var(--surface-deep); cursor: pointer; font: .75rem var(--font-ui); letter-spacing: .04em; text-transform: uppercase; }@media (max-width: 640px) { .pair { grid-template-columns: 1fr; }.heading { align-items: start; gap: 1rem; flex-direction: column; }.owner { display: none; } }
</style>