<script lang="ts">
	import { ArrowLeft, Eye, Image, MessageSquare, Radio, Save, Send, UserRound } from '@lucide/svelte';
	import type { ActionData, PageData } from './$types';
	let { data, form }: { data: PageData; form: ActionData } = $props();
	let title = $state(''); let author = $state(''); let status = $state(''); let note = $state(''); let footer = $state(''); let color = $state(''); let guildId = $state(''); let channelId = $state('');
	$effect(() => { title = data.card.title; author = data.card.author; status = data.card.status; note = data.card.note; footer = data.card.footer; color = data.card.color; guildId = data.card.guildId ?? ''; channelId = data.card.channelId ?? ''; });
</script>

<svelte:head><title>Kuratorin-Karte | Sanctum Theoretica</title></svelte:head>
<main class="sanctum-page antialiased"><header class="sanctum-header"><a href="/" aria-label="Zur Übersicht" title="Zur Übersicht"><ArrowLeft size={18} /></a><div class="brand"><span>ST</span><strong>Kuratorium / Kuratorin</strong></div><nav class="curator-tabs"><a href="/curator-chat"><MessageSquare size={14} /> Schattenfunk</a><a href="/curator-card" class="active"><UserRound size={14} /> Profilkarte & Ritual</a></nav></header><section class="shell sanctum-shell"><div class="heading"><div><p class="eyebrow">Einzelakte · Owner-Only</p><h1>Die Kuratorin</h1></div><span>Unabhängig von /profile</span></div>{#if form?.error}<p class="feedback error">{form.error}</p>{/if}{#if form?.success}<p class="feedback success">Die Kuratorin-Karte wurde gespeichert.</p>{/if}{#if form?.sent}<p class="feedback success">Die Kuratorin hat ihre Akte im Zielkanal hinterlassen.</p>{/if}<div class="grid"><form method="POST" action="?/save" enctype="multipart/form-data" class="editor"><div class="section-label"><UserRound size={16} /> Redaktion</div><label>Autorzeile<input name="author" bind:value={author} maxlength="100" /></label><label>Titel<input name="title" bind:value={title} maxlength="100" /></label><label>Archivstatus<input name="status" bind:value={status} maxlength="100" /></label><label>Archivnotiz<textarea name="note" bind:value={note} maxlength="500"></textarea></label><label>Footer<input name="footer" bind:value={footer} maxlength="150" /></label><label>Akzentfarbe<input name="color" bind:value={color} maxlength="6" /></label><label>Visual ersetzen<input name="image" type="file" accept="image/jpeg,image/png,image/webp" /><small>Optional · JPG, PNG oder WebP · max. 5 MB</small></label><div class="section-label"><Radio size={16} /> Zielort</div><label>Discord-Guild-ID<input name="guildId" bind:value={guildId} inputmode="numeric" placeholder="17 bis 20 Ziffern" /></label><label>Discord-Channel-ID<input name="channelId" bind:value={channelId} inputmode="numeric" placeholder="17 bis 20 Ziffern" /></label><button class="sanctum-button" type="submit"><Save size={16} /> Karte speichern</button></form><aside class="preview"><div class="section-label"><Eye size={16} /> Discord-Vorschau</div><div class="embed" style={`--accent: #${color}`}><div class="embed-author">{author}</div><div class="embed-title">◈ INTERNE AKTE · {title}</div><div class="embed-body"><i>{note}</i><div class="field"><span>Archivstatus</span><b>{status}</b></div></div>{#if data.card.imageKey}<img class="embed-image" src="/media/curator" alt="Visual der Kuratorin" />{/if}<div class="embed-footer">{footer}</div></div><form method="POST" action="?/send" class="send"><button class="sanctum-button" type="submit" disabled={!guildId || !channelId}><Send size={16} /> Jetzt als Kuratorin senden</button><small>Postet die gespeicherte Karte direkt als Bot-Nachricht.</small></form></aside></div></section></main>

<style>
	.curator-tabs { display: flex; gap: 0.5rem; margin-left: auto; }
	.curator-tabs a { display: inline-flex; align-items: center; gap: 0.4rem; padding: 0.45rem 0.8rem; font: 0.72rem var(--font-ui); letter-spacing: 0.05em; text-transform: uppercase; text-decoration: none; color: var(--ink-muted); border: 1px solid transparent; border-radius: 0.25rem; transition: all 0.16s ease; }
	.curator-tabs a:hover { color: var(--ink); border-color: var(--line); }
	.curator-tabs a.active { color: #fff; background: var(--surface-deep); border-color: var(--line); }
	main { min-height: 100vh; background: linear-gradient(118deg, rgba(101, 48, 139, .2), transparent 42%), repeating-linear-gradient(0deg, rgba(160, 97, 208, .07) 0 1px, transparent 1px 5px); }.brand { display: flex; gap: .6rem; align-items: center; font: .78rem var(--font-ui); letter-spacing: .08em; text-transform: uppercase; }.brand span { display: grid; width: 30px; aspect-ratio: 1; place-items: center; color: #fff; background: var(--surface-deep); font-family: var(--font-display); letter-spacing: 0; }.shell { width: min(1120px, 90vw); margin: 4rem auto 7rem; }.heading { display: flex; align-items: end; justify-content: space-between; border-bottom: 1px solid var(--line); padding-bottom: 1.5rem; }.eyebrow, .heading > span, .section-label { margin: 0; color: var(--ink-soft); font: .72rem var(--font-ui); letter-spacing: .1em; text-transform: uppercase; }h1 { margin: .5rem 0 0; font-size: clamp(3rem, 6vw, 5rem); font-weight: 400; line-height: .9; }.grid { display: grid; grid-template-columns: minmax(0, 1fr) minmax(300px, .82fr); gap: 3rem; margin-top: 2rem; }.editor, .preview { display: grid; gap: 1rem; padding: 1.35rem; border: 1px solid var(--line); background: var(--surface-raised); }.section-label { display: flex; gap: .5rem; align-items: center; color: var(--ink); }label { display: grid; gap: .45rem; }input, textarea { width: 100%; border: 1px solid var(--line); border-radius: .25rem; padding: .65rem; color: var(--ink); background: var(--surface-sunken); }textarea { min-height: 120px; resize: vertical; }small { color: var(--ink-muted); font: .72rem var(--font-ui); }.embed { border-left: 4px solid var(--accent); padding: 1rem; color: #dbdee1; background: #2b2d31; font-family: Arial, sans-serif; }.embed-author { margin-bottom: .7rem; font-size: .78rem; font-weight: 700; }.embed-title { font-size: .95rem; font-weight: 700; }.embed-body { margin-top: .8rem; line-height: 1.5; }.field { display: grid; gap: .15rem; margin-top: 1rem; color: #949ba4; font-size: .72rem; }.field b { color: #dbdee1; }.embed-image { width: 100%; max-height: 360px; margin-top: 1rem; object-fit: contain; background: #0c0711; }.embed-footer { margin-top: .9rem; color: #949ba4; font-size: .72rem; }.send { display: grid; gap: .7rem; margin-top: .5rem; }.feedback { margin-top: 1rem; padding: .75rem; }.error { color: #ffc0d2; border-left: 3px solid var(--danger); }.success { color: var(--success); border-left: 3px solid var(--success); }@media (max-width: 760px) { .grid { grid-template-columns: 1fr; }.shell { margin-top: 2.5rem; } }
</style>